---
proxmox_version: "9.0"
proxmox_debian_version: "13"

root_password: "{{ vault_root_password }}"
tailscale_auth_key: "{{ vault_tailscale_auth_key }}"
tailscale_api_token: "{{ vault_tailscale_api_token }}"

zfs_pools:
  - name: ssd-raid
    type: raidz1
    devices:
      - ata-WDC_WDS100T1R0A-68A4W0_241749801378
      - ata-WDC_WDS100T1R0A-68A4W0_22480H800626
      - ata-WDC_WDS100T1R0A-68A4W0_22480H800457
      - ata-WDC_WDS100T1R0A-68A4W0_241749800419
    mountpoint: /ssd-raid
    compression: lz4
    atime: "off"
    xattr: sa
    aclinherit: passthrough

pve_storages:
  - name: local
    type: dir
    path: /var/lib/vz
    content: "vztmpl,iso,backup"
  - name: local-lvm
    type: lvmthin
    vgname: pve
    thinpool: data
    content: "rootdir,images"
  - name: ssd-raid
    type: zfspool
    pool: ssd-raid
    content: "rootdir,images"
  # PBS storage is configured dynamically in 006_pbs-setup.yml

sdn_zones:
  - name: sibzone
    type: simple
    ipam: pve

sdn_vnets:
  - name: sibnet
    zone: sibzone

sdn_subnets:
  - vnet: sibnet
    cidr: 192.168.100.0/24
    gateway: 192.168.100.1
    snat: true
    dhcp_start: 192.168.100.100
    dhcp_end: 192.168.100.200

iommu_enabled: true
iommu_type: amd
vfio_modules:
  - vfio
  - vfio_iommu_type1
  - vfio_pci
  - vfio_virqfd

blacklist_drivers:
  - nvidiafb
  - nouveau
  - nvidia
  - radeon
  - amdgpu

# PBS Configuration
pbs_datastore_path: /mnt/backup-datastore
pbs_disk_device: /dev/disk/by-id/ata-WDC_WD201KFGX-68BKJN0_2LG8D8XF-part1  # 18.2TB HDD for PBS (partition 1)
pbs_datastore_name: backup-store
pbs_wipe_disk: false

# ZFS tuning
zfs_arc_max_ratio: 0.5