---
- name: Network Configuration
  hosts: proxmox
  gather_facts: true
  become: true
  
  tasks:
    - name: Install network utilities
      apt:
        name:
          - ifupdown2
          - bridge-utils
          - ethtool
        state: present
      tags:
        - packages
    
    - name: Configure network interfaces
      template:
        src: ../../templates/proxmox/interfaces.j2
        dest: /etc/network/interfaces
        backup: yes
      notify: restart networking
    
    - name: Configure DNS (skip if managed by systemd-resolved on Debian 12+)
      template:
        src: ../../templates/proxmox/resolv.conf.j2
        dest: /etc/resolv.conf
        mode: '0644'
      when: not (ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] | int >= 12 and ansible_facts.services is defined and 'systemd-resolved.service' in ansible_facts.services)
    
    - name: Set hostname
      hostname:
        name: "{{ proxmox_node_name }}"
    
    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "^{{ proxmox_ip }}\\s+{{ proxmox_node_name }}\\.local\\s+{{ proxmox_node_name }}$"
        line: "{{ proxmox_ip }} {{ proxmox_node_name }}.local {{ proxmox_node_name }}"
        state: present
    
    - name: Enable IP forwarding
      sysctl:
        name: "{{ item }}"
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
      loop:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding
    
    - name: Check if Proxmox firewall directory exists
      stat:
        path: /etc/pve/firewall
      register: pve_firewall_dir
      check_mode: no
    
    - name: Create Proxmox firewall directory if not exists
      file:
        path: /etc/pve/firewall
        state: directory
      when: pve_firewall_dir.stat.exists
      ignore_errors: yes
    
    - name: Write Proxmox firewall configuration using shell
      shell: |
        cat > /etc/pve/firewall/cluster.fw << 'EOF'
        [OPTIONS]
        enable: 1
        policy_in: DROP
        policy_out: ACCEPT
        
        [RULES]
        # Basic Proxmox services
        IN ACCEPT -i vmbr0 -p tcp -dport 8006 # Proxmox web interface
        IN ACCEPT -i vmbr0 -p tcp -dport 8007 # PBS web interface  
        IN ACCEPT -i vmbr0 -p tcp -dport 3128 # SPICE proxy
        IN ACCEPT -i vmbr0 -p tcp -dport 5900:5999 # VNC range
        IN ACCEPT -i vmbr0 -p tcp -dport 22 # SSH
        
        # Tailscale traffic
        IN ACCEPT -p udp -dport 41641 # Tailscale
        
        # Allow established connections
        IN ACCEPT -m conntrack --ctstate ESTABLISHED,RELATED
        EOF
      when: pve_firewall_dir.stat.exists
      register: firewall_config
      changed_when: firewall_config.rc == 0
    
  handlers:
    - name: restart networking
      systemd:
        name: networking
        state: restarted


