---
- name: Stop LXC (best effort) before config changes
  command: pct stop {{ target_lxc_vmid }}
  failed_when: false
  changed_when: false

- name: Ensure TUN device access (needed for Tailscale)
  ansible.builtin.blockinfile:
    path: "/etc/pve/lxc/{{ target_lxc_vmid }}.conf"
    marker: "# {mark} ANSIBLE TUN CONFIG"
    block: |
      lxc.cgroup2.devices.allow: c 10:200 rwm
      lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file

- name: Ensure NVIDIA GPU device access (if present)
  ansible.builtin.blockinfile:
    path: "/etc/pve/lxc/{{ target_lxc_vmid }}.conf"
    marker: "# {mark} ANSIBLE NVIDIA CONFIG"
    block: |
      lxc.cgroup2.devices.allow: c 195:* rwm
      lxc.cgroup2.devices.allow: c 234:* rwm
      lxc.cgroup2.devices.allow: c 508:* rwm
      lxc.cgroup2.devices.allow: c 509:* rwm
      lxc.cgroup2.devices.allow: c 511:* rwm
      lxc.mount.entry: /dev/nvidia0 dev/nvidia0 none bind,optional,create=file
      lxc.mount.entry: /dev/nvidia1 dev/nvidia1 none bind,optional,create=file
      lxc.mount.entry: /dev/nvidiactl dev/nvidiactl none bind,optional,create=file
      lxc.mount.entry: /dev/nvidia-modeset dev/nvidia-modeset none bind,optional,create=file
      lxc.mount.entry: /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file
      lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-uvm-tools none bind,optional,create=file
      lxc.mount.entry: /dev/nvidia-caps dev/nvidia-caps none bind,optional,create=dir
      # Mount NVIDIA driver libraries from host
      lxc.mount.entry: /usr/lib/x86_64-linux-gnu/libcuda.so.1 usr/lib/x86_64-linux-gnu/libcuda.so.1 none bind,optional,create=file
      lxc.mount.entry: /usr/lib/x86_64-linux-gnu/libcuda.so usr/lib/x86_64-linux-gnu/libcuda.so none bind,optional,create=file
      lxc.mount.entry: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 none bind,optional,create=file
      lxc.mount.entry: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so usr/lib/x86_64-linux-gnu/libnvidia-ml.so none bind,optional,create=file
      lxc.mount.entry: /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1 usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1 none bind,optional,create=file
      lxc.mount.entry: /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1 usr/lib/x86_64-linux-gnu/libnvcuvid.so.1 none bind,optional,create=file

- name: Start LXC after config change
  command: pct start {{ target_lxc_vmid }}
  register: start_out
  failed_when: false
  changed_when: start_out.rc == 0


