model = "gpt-5.4"
approval_policy = "never"
sandbox_mode = "danger-full-access"
web_search = "live"
model_reasoning_effort = "xhigh"
plan_mode_reasoning_effort = "xhigh"
personality = "pragmatic"

[mcp_servers.context7]
type = "http"
url = "https://mcp.context7.com/mcp"
env_http_headers = { CONTEXT7_API_KEY = "CONTEXT7_API_KEY" }

[mcp_servers.gh_grep]
url = "https://mcp.grep.app"

[mcp_servers.exa]
url = "https://mcp.exa.ai/mcp"
bearer_token_env_var = "EXA_API_KEY"

[mcp_servers.vercel]
url = "https://mcp.vercel.com"

[mcp_servers.railway]
command = "npx"
args = ["-y", "@railway/mcp-server"]

[notice]
hide_full_access_warning = true

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.4"

[features]
multi_agent = true

[projects."/Users/andrei/git/milkroad-sanity"]
trust_level = "trusted"

[projects."/Users/andrei/git/ai-presentation"]
trust_level = "trusted"

[projects."/Users/andrei/git/houseofstake.org-hos-repo"]
trust_level = "trusted"

[projects."/Users/andrei"]
trust_level = "trusted"

[projects."/Users/andrei/git/andreiv.com"]
trust_level = "trusted"

[projects."/Users/andrei/git/data-commons"]
trust_level = "trusted"

[projects."/Users/andrei/git/dotfiles"]
trust_level = "trusted"

[projects."/Users/andrei/git/hos-api"]
trust_level = "trusted"

[projects."/Users/andrei/git/nicepfp.art"]
trust_level = "trusted"

[projects."/Users/andrei/git/openinvoice"]
trust_level = "trusted"

[projects."/Users/andrei/git/pulse"]
trust_level = "trusted"

[projects."/Users/andrei/git/rh-portfolio-tracker"]
trust_level = "trusted"

[projects."/Users/andrei/git/hh-near-journey"]
trust_level = "trusted"

[projects."/Users/andrei/git/silent-mesh"]
trust_level = "trusted"

[projects."/Users/andrei/git/silent-mesh-rust"]
trust_level = "trusted"

[projects."/Users/andrei/git/milkroad-portfolio"]
trust_level = "trusted"

[projects."/Users/andrei/git/hos-intel"]
trust_level = "trusted"

[projects."/Users/andrei/git/silentmesh-ultra"]
trust_level = "trusted"

[projects."/Users/andrei/git/open-interns"]
trust_level = "trusted"

[plugins."github@openai-curated"]
enabled = true

[plugins."stripe@openai-curated"]
enabled = true
